# Generated by Django 4.2 on 2025-02-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_computadoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('laptops', 'Laptops/Notebooks'), ('hardware', 'Hardware'), ('escritorio', 'Computadoras de Escritorio')], default='laptops', max_length=20),
        ),
    ]
